import customtkinter
import CardDexTools


app = customtkinter.CTk()
app.geometry("500x500")
app.title("CardDex v1.2 stable")


#frame menu
frame_menu = customtkinter.CTkFrame(app)
frame_menu.pack(pady=10, padx=10)
titulo_menu = customtkinter.CTkLabel(frame_menu, text="Menu", font=("Arial", 18))
titulo_menu.pack(pady=5)
btn_ver = customtkinter.CTkButton(frame_menu, text="Ver", fg_color="#2e4bcc", hover_color="#29badf", command=lambda:CardDexTools.mostrar_ver(frame_menu, frame_ver))
btn_ver.pack(side="left", pady=10, padx=5)
btn_adc = customtkinter.CTkButton(frame_menu, text="Adicionar", fg_color="#2e4bcc", hover_color="#29badf", command=lambda:CardDexTools.mostrar_ver(frame_menu, frame_adc))
btn_adc.pack(side="top", pady=10, padx=5)
btn_rem = customtkinter.CTkButton(frame_menu, text="Remover", fg_color="#2e4bcc", hover_color="#29badf", command=lambda:CardDexTools.mostrar_ver(frame_menu, frame_remov))
btn_rem.pack(side="right", pady=10, padx=5)

#frame ver
frame_ver = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_ver = customtkinter.CTkLabel(frame_ver, text="Lista de cartas", font=("Arial", 16, "bold"))
titulo_ver.pack(pady=10)
ver_file = customtkinter.CTkEntry(frame_ver, placeholder_text="Nome da Lista...")
ver_file.pack(pady=10)
btn_verfl = customtkinter.CTkButton(frame_ver, text="Ver lista", command=lambda:CardDexTools.acao_ver_lista(ver_file, label_ver))
btn_verfl.pack(pady=10)
btn_verret = customtkinter.CTkButton(frame_ver, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_ver, frame_menu))
btn_verret.pack(pady=10)
label_ver = customtkinter.CTkLabel(frame_ver, text="")
label_ver.pack(pady=10)

#frame adicionar
frame_adc = customtkinter.CTkFrame(app,fg_color="transparent")
titulo_adc = customtkinter.CTkLabel(frame_adc, text="Adicionar cartas", font=("Arial", 16, "bold"))
titulo_adc.pack(pady=10)
btn_adcex = customtkinter.CTkButton(frame_adc, text="Lista Existente", command=lambda:CardDexTools.mostrar_ver(frame_adc, frame_adcex))
btn_adcex.pack(side="left", pady=10)
btn_adcret = customtkinter.CTkButton(frame_adc, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_adc, frame_menu))
btn_adcret.pack(pady=10)
btn_adcnw = customtkinter.CTkButton(frame_adc, text="Lista Nova", command=lambda:CardDexTools.mostrar_ver(frame_adc, frame_adcnw))
btn_adcnw.pack(side="right", pady=10)

#frame adicionar a existente
frame_adcex = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_adcex = customtkinter.CTkLabel(frame_adcex, text="Adicionar cartas", font=("Arial", 16, "bold"))
titulo_adcex.pack(pady=10)
entry_file = customtkinter.CTkEntry(frame_adcex, placeholder_text="Nome da Lista...")
entry_file.pack(pady=10)
btn_verli = customtkinter.CTkButton(frame_adcex, text="Ver lista", command=lambda:CardDexTools.acao_verif_lista(entry_file, label_adcex, frame_adcex, frame_adcexinf, titulo_adcexinf))
btn_verli.pack(pady=10)
btn_adcexret = customtkinter.CTkButton(frame_adcex, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_adcex, frame_menu))
btn_adcexret.pack(pady=10)
label_adcex = customtkinter.CTkLabel(frame_adcex, text="")
label_adcex.pack(pady=10)

#frame adicionar nomes e telemoveis a existente
frame_adcexinf = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_adcexinf = customtkinter.CTkLabel(frame_adcexinf, text=f"Adicionar cartas a ...", font=("Arial", 16, "bold"))
titulo_adcexinf.pack(pady=10)
entry_nome = customtkinter.CTkEntry(frame_adcexinf, placeholder_text="Nome")
entry_nome.pack(side="left", pady=10)
entry_tel = customtkinter.CTkEntry(frame_adcexinf, placeholder_text="Tipo")
entry_tel.pack(side="right", pady=10)
btn_adcexinf = customtkinter.CTkButton(frame_adcexinf, text="Adicionar", command=lambda:CardDexTools.acao_adicionar_existente(entry_file, entry_nome, entry_tel, label_adcexinf))
btn_adcexinf.pack(pady=10)
btn_adcexiret = customtkinter.CTkButton(frame_adcexinf, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_adcexinf, frame_menu))
btn_adcexiret.pack(pady=10)
label_adcexinf = customtkinter.CTkLabel(frame_adcexinf, text="")
label_adcexinf.pack(pady=10)

#frame adicionar numeros a lista nova
frame_adcnw = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_adcnw = customtkinter.CTkLabel(frame_adcnw, text=f"Adicionar cartas", font=("Arial", 16, "bold"))
titulo_adcnw.pack(pady=10)
newadclis = customtkinter.CTkEntry(frame_adcnw, placeholder_text="Nome da Lista Nova...")
newadclis.pack(pady=10)
btn_adcnw = customtkinter.CTkButton(frame_adcnw, text="Criar Lista", command=lambda:CardDexTools.criar_file(newadclis, frame_adcnw, frame_adcnwinf, titulo_adcnwinf, label_adcnw))
btn_adcnw.pack(pady=10)
btn_adcnwret = customtkinter.CTkButton(frame_adcnw, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_adcnw, frame_menu))
btn_adcnwret.pack(pady=10)
label_adcnw = customtkinter.CTkLabel(frame_adcnw, text="")
label_adcnw.pack(pady=10)

#frame adicionar nomes e telemoveis a nova
frame_adcnwinf = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_adcnwinf = customtkinter.CTkLabel(frame_adcnwinf, text=f"Adicionar cartas a ...", font=("Arial", 16, "bold"))
titulo_adcnwinf.pack(pady=10)
newadcnome = customtkinter.CTkEntry(frame_adcnwinf, placeholder_text="Nome")
newadcnome.pack(side="left", pady=10)
newadctef = customtkinter.CTkEntry(frame_adcnwinf, placeholder_text="Tipo")
newadctef.pack(side="right", pady=10)
btn_adcnwinf = customtkinter.CTkButton(frame_adcnwinf, text="Adicionar", command=lambda:CardDexTools.acao_adicionar_existente(newadclis, newadcnome, newadctef, label_adcnwinf))
btn_adcnwinf.pack(pady=10)
btn_adcnwret = customtkinter.CTkButton(frame_adcnwinf, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_adcnwinf, frame_menu))
btn_adcnwret.pack(pady=10)
label_adcnwinf = customtkinter.CTkLabel(frame_adcnwinf, text="")
label_adcnwinf.pack(pady=10)

#frame remover
frame_remov = customtkinter.CTkFrame(app, fg_color="transparent")
titulo_remov = customtkinter.CTkLabel(frame_remov, text="Remover", font=("Arial", 16, "bold"))
titulo_remov.pack(pady=10)
btnremct = customtkinter.CTkButton(frame_remov, text="Cartas", command=lambda:CardDexTools.mostrar_ver(frame_remov, frame_remov_con))
btnremct.pack(side="left", pady=10)
btn_remret = customtkinter.CTkButton(frame_remov, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_remov, frame_menu))
btn_remret.pack(pady=10)
btnremlis = customtkinter.CTkButton(frame_remov, text="Lista", command=lambda:CardDexTools.mostrar_ver(frame_remov, frame_removlist))
btnremlis.pack(side="right", pady=10)

#frame remover lista
frame_removlist = customtkinter.CTkFrame(app, fg_color="transparent")
label_removlist = customtkinter.CTkLabel(frame_removlist, text=f"Remover Lista", font=("Arial", 16, "bold"))
label_removlist.pack(pady=10)
newremovli = customtkinter.CTkEntry(frame_removlist, placeholder_text="Nome da Lista a remover...")
newremovli.pack(pady=10)
btnreml = customtkinter.CTkButton(frame_removlist, text="Remover Lista", command=lambda:CardDexTools.acao_eliminar_lista(newremovli, label_resultrem))
btnreml.pack(pady=10)
btn_remvret = customtkinter.CTkButton(frame_removlist, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_removlist, frame_menu))
btn_remvret.pack(pady=10)
label_resultrem = customtkinter.CTkLabel(frame_removlist, text="")
label_resultrem.pack(pady=10)

#frame remover contactos
frame_remov_con = customtkinter.CTkFrame(app, fg_color="transparent")
label_removcon = customtkinter.CTkLabel(frame_remov_con, text=f"Remover cartas", font=("Arial", 16, "bold"))
label_removcon.pack(pady=10)
newremovcon = customtkinter.CTkEntry(frame_remov_con, placeholder_text="Nome da Lista a Remover Cartas...")
newremovcon.pack(pady=10)
btnremovcon = customtkinter.CTkButton(frame_remov_con, text="Selecionar Lista", command=lambda:CardDexTools.acao_verif_lista(newremovcon, label_resultremcon, frame_remov_con, frame_remov_con_li , label_removconli))
btnremovcon.pack(pady=10)
btn_remvret = customtkinter.CTkButton(frame_remov_con, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_remov_con, frame_menu))
btn_remvret.pack(pady=10)
label_resultremcon = customtkinter.CTkLabel(frame_remov_con, text="")
label_resultremcon.pack(pady=10)

#frame remover contactos da lista
frame_remov_con_li = customtkinter.CTkFrame(app, fg_color="transparent")
label_removconli = customtkinter.CTkLabel(frame_remov_con_li, text="Remover cartas de...", font=("Arial", 16, "bold"))
label_removconli.pack(pady=10)
newremovconli = customtkinter.CTkEntry(frame_remov_con_li, placeholder_text="Nome da carta...")
newremovconli.pack(pady=10)
btnremovconli = customtkinter.CTkButton(frame_remov_con_li, text="Remover Carta", command=lambda:CardDexTools.remover_carta(newremovcon, newremovconli))
btnremovconli.pack(pady=10)
btn_remvret = customtkinter.CTkButton(frame_remov_con_li, text="Menu", command=lambda:CardDexTools.mostrar_ver(frame_remov_con_li, frame_menu))
btn_remvret.pack(pady=10)
label_resultremconli = customtkinter.CTkLabel(frame_remov_con_li, text="")
label_resultremconli.pack(pady=10)


app.mainloop()